# Generated by Django 3.2.4 on 2021-07-08 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
